name: Run JS with Secret

on: [push]  # or 'workflow_dispatch' to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script with API key
        run: node your-script.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
